### ISSUE TITLE
Official Mod Suggestions for All The Magic

### ISSUE THREAD

**Issue by Yoosk** [AllTheMods/AllTheMagic#1]
Just leave a comment and and link to Curseforge project.
-

**If your comment has been deleted or hidden do not panic, it just means I have tidied up the ones I have added to this list or turned down**

Under Consideration: 

Needs tweaking/fixes: 

Please list your recommendation with a link to it's CurseForge profile page.

**Comment by Radient-Sora** [comment]
added (closed)

**Comment by AGithub457** [comment]
https://minecraft.curseforge.com/projects/mod-name-tooltip

Gives tooltips underneath the mod items like WAILA used to, but for TOP.

**Comment by Radient-Sora** [comment]
Consider it done, next update
