### ISSUE TITLE
Crafting natural altar requires impossible sapling

### ISSUE THREAD

**Issue by monkeybug34** [AllTheMods/AllTheMagic#11]
## Expected Behavior
crafting recipe should use a sapling that can grow in a 1x1 sapling pattern

## Current Behavior
the recipe for the natural altar from nature's aura is non-craftable because the recipe uses a sapling that does ot fit inside the ritual area.

## Possible Solution

fix the recipe imlemented to use a different sapling.

## Steps to Reproduce

1. attempt to craft the natural altar
3.
4.

## Detailed Description

please change the sapling required to craft the natural altar to a sapling that grows as a 1x1, not a 2x2 exclusively. dark oak and greatwood are examples of 2x2 exclusive trees.

**Comment by FallenEagle1** [comment]
Fixed in 1.6.0 Update
