### ISSUE TITLE
Embers Melt Dupped using HammerX Stone Hammer

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/AllTheMagic#2]
## Expected Behavior
When breaking an Embers Melter only one Melter dropped item is expected.

## Current Behavior
I had a stone hammer from HammerX and was attempting to pick up an Embers Melter I put down; I didn't have any pickaxes. When destroying the Melter with the hammer it dropped two Melters. I tried this twice with the same results. I now have three but only made one.

I then tried using an iron pickaxe from Adventure's Toolbox and it only dropped one Melter when destroyed which is the expected behavior.

## Possible Solution
Not sure. I only produced the HammerX stone hammer trying to make a stone pickaxe. So this will likely be easily discovered.

## Steps to Reproduce
1. Place an Embers Melter in the world; in my test I placed it on both stone and cobblestone.
2. Use a HammerX stone hammer to break the Melter.
3. Two dropped Melters will appear and can be picked up.

## Log
No Crash or log created.

## Detailed Description

Noob suggestion is to determine and fix dupping bug :P

**Comment by juryjr** [comment]
as of alpha 1.5.1 its still an issue

**Comment by UpcraftLP** [comment]
@Radient-Sora fix your shit xD

**Comment by Radient-Sora** [comment]
fixed (removed mods causing issues)
