### ISSUE TITLE
Mod Nature's Aura is Inaccessible

### ISSUE THREAD

**Issue by Xedea** [AllTheMods/AllTheMagic#23]
## Expected Behavior

The item Natural Altar should be craftable using the "Ritual of the Forest" crafting method of Nature's Aura. This method is triggered by the growth of a sappling in the 1x1 center of the structure.

## Current Behavior

The item cannot be crafted because the recipe has been changed to use a greatwood sappling instead. Greatwood saplings cannot grow with just one sapling meaning the ritual can never triggered to begin.

## Possible Solution

Change the recipe.

## Steps to Reproduce

1. Attempt to create the item "Natural Altar" from the Nature's Aura mod.
2.
3.
4.

**Comment by FallenEagle1** [comment]
Update, as that is an old version of the pack and that was fixed in the last update
