### ISSUE TITLE
Tweak AkashicTome's config

### ISSUE THREAD

**Issue by zet4** [AllTheMods/AllTheMagic#3]
In current default config of AkashicTome some items that should be in the whitelist, are not, and some are in it though they shouldn't be.

## Expected Behavior
Blob's Wizardry Spell books **can't** be added to the tome
EvilCraft's book **can** be added to the tome

## Current Behavior
Blob's Wizardry Spell books **can** be added to the tome
EvilCraft's book **can't** be added to the tome

## Possible Solution
Whitelist EvilCraft's book and blacklist Blob's Wizardry Spell books.

**Comment by FallenEagle1** [comment]
I actually like the idea of the spell books, the take up so much room. But the book does need some tweaking. That's why the pack is still alpha, it is still being worked on and hasn't truly had a release yet.

**Comment by Radient-Sora** [comment]
closed
