### ISSUE TITLE
Starting a new world has prefilled JEI content

### ISSUE THREAD

**Issue by AGithub457** [AllTheMods/AllTheMagic#4]
## Expected Behavior

When starting a new world on the new modpack, JEI should be cleared and not in cheat mode.

## Current Behavior

A new world has "olives" bookmarked, cheat mode on (even when world cheats are off), and search set to "thaum".

## Possible Solution

Delete jei/bookmarks.ini and jei/worldsettings.cfg from the releases

## Steps to Reproduce

1. Start a new world
2. [Result](https://imgur.com/a/OajgJTC)
3.
4.

**Comment by FallenEagle1** [comment]
Taken care of now, and will be aware of it for next updates as well
