### ISSUE TITLE
It crashes I reinstalled it the pack ran once then after it started to constantly crashes again

### ISSUE THREAD

**Issue by the-guy1** [AllTheMods/AllTheMagic#9]
## Steps to Reproduce

1.
2.
3.
4.

## Log

[Crash report]{https://pastebin.com/thLQHQrt)

**Comment by Someone1002** [comment]
so you know that green bar at the top when its loading? if it touches the red marker line, the game crashes. to stop this, the game does a "core" dump", when it has the green bar jump back. the crash says it failed when trying to do the core dump and touched the red line. happens to most people, you just need to keep opening it a few times. helps to keep minecraft open and not have much else open. if you use twitch to launch, theres another possible thing that could help. if you go to settings->minecraft->scroll to java->allocated memory slider->recommended bit for this is 6 GB

**Comment by FallenEagle1** [comment]
I would check with the new update if this still persists

**Comment by Boomflex** [comment]
Also worth updating your Java too as you’re on a quite old version. 

You may have to manually tell the Twitch App to use the latest if you’ve downloaded the latest.
